name: ${project.artifactId}
version: ${project.version}
main: net.okocraft.toggledeathmessage.Main
author: LazyGon
api-version: '1.19'
depend: ["ProtocolLib"]

commands:
  toggledeathmessage:
    aliases: ["tdm"]
    permission: "toggledeathmessage.toggle"
    description: デスメッセージが聞こえるかどうかを切り替えるコマンド。

permissions:
  toggledeathmessage.toggle:
    default: true
    description: tdmコマンドの権限